apiVersion: apps/v1
kind: Deployment
metadata:
  name: tysoncloud
  labels:
    app: tysoncloud
spec:
  selector:
    matchLabels:
      app: tysoncloud
  template:
    metadata:
      labels:
        app: tysoncloud
    spec:
      containers:
        - name: payme
          image: timmijinks/payme
          ports:
            - containerPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tysoncloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tysoncloud
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
